name: Sync-BPB-Worker-Panel

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync-content:
    permissions:  # 关键权限配置
      contents: write
    runs-on: ubuntu-latest

    steps:
    - name: 检出仓库
      uses: actions/checkout@v4
      with:
        ref: main

    - name: 下载资产
      run: |
        curl -L -o worker.js "https://github.com/bia-pain-bache/BPB-Worker-Panel/raw/main/worker.js"
        curl -L -o worker.zip "https://github.com/bia-pain-bache/BPB-Worker-Panel/raw/main/worker.zip"
        curl -L -o source-code.zip "https://github.com/bia-pain-bache/BPB-Worker-Panel/raw/main/source-code.zip"

    - name: 提交更改
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git add worker.js worker.zip source-code.zip
        git commit -m "chore: 同步BPB-Worker-Panel资产 [skip ci]" || echo "没有更改需要提交"
        git push origin main
