name: Sync-BPB-Worker-Panel

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync-content:
    permissions:
      contents: write
      issues: write
    runs-on: ubuntu-latest

    steps:
    - name: 检出仓库（完整历史）
      uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: 0  # 获取完整提交历史

    - name: 下载资产
      run: |
        curl -L -o worker.js "https://github.com/bia-pain-bache/BPB-Worker-Panel/raw/main/worker.js"
        curl -L -o worker.zip "https://github.com/bia-pain-bache/BPB-Worker-Panel/raw/main/worker.zip"
        curl -L -o source-code.zip "https://github.com/bia-pain-bache/BPB-Worker-Panel/raw/main/source-code.zip"

    - name: 生成详细变更日志
      id: changelog
      run: |
        # 获取自上次同步以来的提交历史
        COMMITS=$(git log --pretty=format:"%h%x09%an%x09%ad%x09%s" --date=format:'%Y-%m-%d %H:%M:%S' --reverse HEAD~1..)
        
        # 生成格式化变更日志
        echo "# 变更日志" > CHANGELOG.md
        echo "" >> CHANGELOG.md
        
        while IFS=$'\t' read -r hash author date message; do
          echo "## [${hash}](https://github.com/${{ github.repository }}/commit/${hash}) (${date})" >> CHANGELOG.md
          echo "**${author}**" >> CHANGELOG.md
          echo "" >> CHANGELOG.md
          
          # 获取完整提交消息
          full_message=$(git log -1 --pretty=format:"%b" $hash)
          echo "$full_message" | while read line; do
            echo "- $line" >> CHANGELOG.md
          done
          
          echo "" >> CHANGELOG.md
        done <<< "$COMMITS"
        
        # 生成版本标签
        VERSION_TAG="v$(date -u +'%Y.%m.%d-%H%M')-sync"
        echo "version_tag=$VERSION_TAG" >> $GITHUB_OUTPUT
        echo "changelog<<EOF" >> $GITHUB_OUTPUT
        cat CHANGELOG.md >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: 提交更改
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        
        # 添加所有变更文件和更新说明
        git add worker.js worker.zip source-code.zip CHANGELOG.md
        
        # 创建带版本标签的提交
        git commit -m "chore: 同步BPB-Worker-Panel资产 [skip ci]
        
        ${{ steps.changelog.outputs.changelog }}"
        
        # 推送代码和标签
        git push origin main
        git tag ${{ steps.changelog.outputs.version_tag }}
        git push origin ${{ steps.changelog.outputs.version_tag }}
